apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-helloworld
  namespace: tp-devops
  labels:
    app: demo-helloworld
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-helloworld
  template:
    metadata:
      labels:
        app: demo-helloworld
    spec:
      containers:
      - name: demo-helloworld
        image: ghofrane13/demo-helloworld:latest
        ports:
        - containerPort: 8082
        env:
        - name: JAVA_OPTS
          value: "-Xmx256m -Xms128m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: demo-helloworld-service
  namespace: tp-devops
  labels:
    app: demo-helloworld
spec:
  selector:
    app: demo-helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer
