apiVersion: v1
kind: Service
metadata:
  name: demo-helloworld-service
  namespace: tp-devops
spec:
  selector:
    app: demo-helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8086
  type: LoadBalancer